version: '3.8'

services:
  app:
    image: ${DOCKER_HUB_USERNAME}/${DOCKER_HUB_REPO_NAME}:${IMAGE_TAG:-latest}
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: rolling-update
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "9000:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    driver: overlay